### ISSUE TITLE
Dice metric in almost_isbi15_score outputs zero every iteration

### ISSUE THREAD

**Issue by ptohidi** [jcreinhold/tiramisu-brulee#6]
## 🐛 Bug

I was training the model on lesion segmentation data (using the cli tools), and wrote "print(dice)" after line 52 of tiramisu_brulee.experiments.lesion_tools (which is "dice = dice_score(pred.int(), target.int())") and the code printed 0 at every iteration. 

To fix this, I used the "dice_loss" function from "tiramisu_brulee.loss" instead of the dice function supplied by torchmetrics, and it seems to works as expected.

## To Reproduce

1. Add print(dice) statement
2. Run code
3. ???
4. Profit

## Additional context

I encountered this issue when I was training a 3D tiramisu network for supervised binary lesion segmentation using 4 input channels (T1, T2, FLAIR, PD).

**Comment by jcreinhold** [comment]
Thanks for the report. I'll look into this.

**Comment by jcreinhold** [comment]
Fixed with da3377ac6865cdea3873a8924b8f6b8705a594c9. Re-install the package and verify that you're using version 0.1.19. Re-open the issue if the problem persists. Thanks for the report!
